[options]
admin_passwd = admin
db_host = db
db_port = 5432
db_user = odoo19
db_password = odoo19
addons_path=/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
logfile=/var/log/odoo/odoo.log
proxy_mode=True
