name: Odoo 19 CI

on:
  push:
    branches:
      - "19.0"
      - "staging"
      - "production"

  pull_request:
    branches:
      - "19.0"
      - "staging"
      - "production"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate Docker Compose
        run: docker compose config

      - name: Build Docker Image
        run: docker build -t odoo19 .

      - name: Start Containers
	  run: docker compose up -d

      - name: Show Running Containers
	  run: docker ps

      - name: Wait for Odoo
	  run: |
	    echo "Waiting for Odoo to start..."
	    for i in {1..30}; do
	      if curl -f http://localhost:1069 >/dev/null 2>&1; then
		echo "Odoo is running!"
		exit 0
	      fi
	      echo "Attempt $i/30..."
	      sleep 5
	    done
	    echo "Odoo failed to start."
	    docker logs odoo19
	    exit 1

	- name: Show Odoo Logs
	  if: always()
	  run: docker logs odoo19 || true

	- name: Stop Containers
	  if: always()
	  run: docker compose down


